AWSTemplateFormatVersion: '2010-09-09'
Description: A stack for the Gerrit service Route53 routing.
Parameters:
  Master1ServiceStackName:
      Description: Stack name of the ECS Master Gerrit service
      Type: String
      Default: gerrit-service-master-1
  Master2ServiceStackName:
      Description: Stack name of the ECS Master Gerrit service
      Type: String
      Default: gerrit-service-master-2

Resources:
  Master1DnsRecord:
      Type: AWS::Route53::RecordSet
      Properties:
        Name:
          !Join
            - '.'
            - - Fn::ImportValue: !Join [':', [!Ref 'Master1ServiceStackName', 'Subdomain']]
              - Fn::ImportValue: !Join [':', [!Ref 'Master1ServiceStackName', 'HostedZoneName']]
        HostedZoneName:
          !Join
            - ''
            - - Fn::ImportValue: !Join [':', [!Ref 'Master1ServiceStackName', 'HostedZoneName']]
              - '.'
        Comment: DNS name for Gerrit Master.
        Type: A
        AliasTarget:
          DNSName:
            Fn::ImportValue:
              !Join [':', [!Ref 'Master1ServiceStackName', 'PublicLoadBalancerDNSName']]
          HostedZoneId:
            Fn::ImportValue:
              !Join [':', [!Ref 'Master1ServiceStackName', 'CanonicalHostedZoneID']]
          EvaluateTargetHealth: False
  Master2DnsRecord:
      Type: AWS::Route53::RecordSet
      Properties:
        Name:
          !Join
            - '.'
            - - Fn::ImportValue: !Join [':', [!Ref 'Master2ServiceStackName', 'Subdomain']]
              - Fn::ImportValue: !Join [':', [!Ref 'Master2ServiceStackName', 'HostedZoneName']]
        HostedZoneName:
          !Join
            - ''
            - - Fn::ImportValue: !Join [':', [!Ref 'Master2ServiceStackName', 'HostedZoneName']]
              - '.'
        Comment: DNS name for Gerrit Master.
        Type: A
        AliasTarget:
          DNSName:
            Fn::ImportValue:
              !Join [':', [!Ref 'Master2ServiceStackName', 'PublicLoadBalancerDNSName']]
          HostedZoneId:
            Fn::ImportValue:
              !Join [':', [!Ref 'Master2ServiceStackName', 'CanonicalHostedZoneID']]
          EvaluateTargetHealth: False
