# AWS general settings
AWS_PREFIX=gerrit
AWS_REGION=us-east-1
CLUSTER_KEYS=$(AWS_PREFIX)-cluster-keys

cluster-keys:
	aws ec2 describe-key-pairs --key-names $(CLUSTER_KEYS) > /dev/null 2>&1 || \
		aws ec2 create-key-pair --key-name $(CLUSTER_KEYS) --query 'KeyMaterial' --output text > $(CLUSTER_KEYS).pem

# Gerrit version
GERRIT_VERSION=3.1
GERRIT_PATCH=4
GERRIT_BRANCH=stable-$(GERRIT_VERSION)

# Gerrit CI
GERRIT_CI=https://gerrit-ci.gerritforge.com/view/Plugins-$(GERRIT_BRANCH)/job
LAST_BUILD=lastSuccessfulBuild/artifact/bazel-bin/plugins

# Image version
HEAD_SHA1=$(shell git log -1 --format=format:%h)
IMAGE_TAG=$(GERRIT_VERSION).$(GERRIT_PATCH)-$(HEAD_SHA1)
