AWSTemplateFormatVersion: '2010-09-09'
Description: A stack for the Monitoring service Route53 routing.
Parameters:
  PrometheusServiceStackName:
      Description: Stack name of the ECS Prometheus service
      Type: String
      Default: gerrit-prometheus
  GrafanaServiceStackName:
      Description: Stack name of the ECS Grafana service
      Type: String
      Default: gerrit-grafana

Resources:
  PrometheusDnsRecord:
      Type: AWS::Route53::RecordSet
      Properties:
        Name:
          !Join
            - '.'
            - - Fn::ImportValue: !Join [':', [!Ref 'PrometheusServiceStackName', 'Subdomain']]
              - Fn::ImportValue: !Join [':', [!Ref 'PrometheusServiceStackName', 'HostedZoneName']]
        HostedZoneName:
          !Join
            - ''
            - - Fn::ImportValue: !Join [':', [!Ref 'PrometheusServiceStackName', 'HostedZoneName']]
              - '.'
        Comment: DNS name for Prometheus.
        Type: A
        AliasTarget:
          DNSName:
            Fn::ImportValue:
              !Join [':', [!Ref 'PrometheusServiceStackName', 'PublicLoadBalancerDNSName']]
          HostedZoneId:
            Fn::ImportValue:
              !Join [':', [!Ref 'PrometheusServiceStackName', 'CanonicalHostedZoneID']]
          EvaluateTargetHealth: False
  GrafanaDnsRecord:
      Type: AWS::Route53::RecordSet
      Properties:
        Name:
          !Join
            - '.'
            - - Fn::ImportValue: !Join [':', [!Ref 'GrafanaServiceStackName', 'Subdomain']]
              - Fn::ImportValue: !Join [':', [!Ref 'GrafanaServiceStackName', 'HostedZoneName']]
        HostedZoneName:
          !Join
            - ''
            - - Fn::ImportValue: !Join [':', [!Ref 'GrafanaServiceStackName', 'HostedZoneName']]
              - '.'
        Comment: DNS name for Grafana.
        Type: A
        AliasTarget:
          DNSName:
            Fn::ImportValue:
              !Join [':', [!Ref 'GrafanaServiceStackName', 'PublicLoadBalancerDNSName']]
          HostedZoneId:
            Fn::ImportValue:
              !Join [':', [!Ref 'GrafanaServiceStackName', 'CanonicalHostedZoneID']]
          EvaluateTargetHealth: False
