{
 "title": "Gerrit",
 "description": "Metrics dashboard for Gerrit multi-site",
 "tags": [ "prometheus" ],
 "time": { "from": "2020-04-21T05:35:35.287Z", "to": "2020-04-21T12:11:11.551Z" },
 "templating": {
  "list": [
   { "name": "Application", "label": "Application", "query": "javamelody_system_load_avg" },
   { "name": "Window", "label": "Aggregation window", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "SSH Conn primary",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max_over_time(sshd_sessions_connected{instance=\"{{PRIMARY_URL}}:443\"}[$Window])"
    }
   ]
  },
  {
   "title": "SSH Conn replica",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max_over_time(sshd_sessions_connected{instance=\"{{REPLICA_URL}}:443\"}[$Window])"
    }
   ]
  },
  { "title": "Live Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "% Cpu Load",
   "type": "graph",
   "description": "system cpu load",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "avg_over_time(javamelody_system_cpu_load_pct[$Window])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}",
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "JGit Cache",
   "type": "graph",
   "description": "used memory for JGit cache in bytes",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "avg_over_time(jgit_block_cache_cache_used[$Window])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}",
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "graph",
   "description": "used memory in bytes",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "avg_over_time(javamelody_memory_used_bytes[$Window])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}",
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "HTTP 500",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(http_server_error_count_500_total[$Window])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SSH Authentication Failures",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(sshd_sessions_authentication_failures_total[$Window])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "System Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "System Load",
   "type": "graph",
   "description": "system load average",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "avg_over_time(javamelody_system_load_avg[$Window])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}",
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "description": "gc time",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(javamelody_memory_gc_millis[$Window])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}",
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Active Threads",
   "type": "graph",
   "description": "active thread count",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "avg_over_time(javamelody_threads_active_count[$Window])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}",
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Unix File Descriptors Open Count",
   "type": "graph",
   "description": "unix open file descriptors count",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "avg_over_time(javamelody_system_unix_file_descriptors_open_count[$Window])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}",
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "HTTP requests mean time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "delta(javamelody_http_duration_millis[$Window])/delta(javamelody_http_hits_count[$Window])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP hits per minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "delta(javamelody_http_hits_count[$Window])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}",
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "% of HTTP Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "delta(javamelody_http_errors_count[$Window])/delta(javamelody_http_hits_count[$Window])*100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}",
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Git", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Git upload pack - count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(git_upload_pack_request_count_total_total[$Window])",
     "legendFormat": "{{instance}} Tot git upload pack"
    }
   ]
  },
  {
   "title": "Git clone and fetch count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(git_upload_pack_request_count_CLONE_total[$Window])",
     "legendFormat": "{{instance}} Tot Clone"
    },
    {
     "expr": "increase(git_upload_pack_request_count_FETCH_total[$Window])",
     "legendFormat": "{{instance}} Tot Fetch"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Scheduled Tasks Queues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(queue_index_batch_total_scheduled_tasks_count[$Window])",
     "legendFormat": "{{instance}} Index"
    },
    {
     "expr": "delta(queue_receive_commits_total_scheduled_tasks_count[$Window])",
     "legendFormat": "{{instance}} Receive Commits"
    },
    {
     "expr": "delta(queue_work_queue_total_scheduled_tasks_count[$Window])",
     "legendFormat": "{{instance}} Tasks"
    },
    {
     "expr": "delta(queue_ssh_command_start_total_scheduled_tasks_count[$Window])",
     "legendFormat": "{{instance}} SSH Command start"
    }
   ]
  }
 ]
}