AWSTemplateFormatVersion: '2010-09-09'
Description: A stack for the Gerrit service Route53 routing.
Parameters:
  ServiceStackName:
      Description: Stack name of the ECS Gerrit service
      Type: String
      Default: gerrit-service

Resources:
  GerritSSHDnsRecord:
      Type: AWS::Route53::RecordSet
      Properties:
        Name:
          !Join
            - '.'
            - - Fn::ImportValue: !Join [ ':', [ !Ref 'ServiceStackName', 'SshSubdomain' ] ]
              - Fn::ImportValue: !Join [ ':', [ !Ref 'ServiceStackName', 'HostedZoneName' ] ]
        HostedZoneName:
          !Join
            - ''
            - - Fn::ImportValue: !Join [':', [!Ref 'ServiceStackName', 'HostedZoneName']]
              - '.'
        Comment: DNS name for Load Balancer serving SSH requests to primary gerrit
        Type: A
        AliasTarget:
          DNSName:
            Fn::ImportValue:
              !Join [':', [!Ref 'ServiceStackName', 'GerritSSHLoadBalancerDNSName']]
          HostedZoneId:
            Fn::ImportValue:
              !Join [':', [!Ref 'ServiceStackName', 'GerritSSHCanonicalHostedZoneID']]
          EvaluateTargetHealth: False

  GerritHTTPDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Name:
        !Join
          - '.'
          - - Fn::ImportValue: !Join [ ':', [ !Ref 'ServiceStackName', 'HttpSubdomain' ] ]
            - Fn::ImportValue: !Join [ ':', [ !Ref 'ServiceStackName', 'HostedZoneName' ] ]
      HostedZoneName:
        !Join
        - ''
        - - Fn::ImportValue: !Join [':', [!Ref 'ServiceStackName', 'HostedZoneName']]
          - '.'
      Comment: DNS name for Load Balancer serving HTTP requests to primary gerrit
      Type: A
      AliasTarget:
        DNSName:
          Fn::ImportValue:
            !Join [':', [!Ref 'ServiceStackName', 'GerritHTTPLoadBalancerDNSName']]
        HostedZoneId:
          Fn::ImportValue:
            !Join [':', [!Ref 'ServiceStackName', 'GerritHTTPCanonicalHostedZoneID']]
        EvaluateTargetHealth: False