AWSTemplateFormatVersion: '2010-09-09'
Description: A stack for the Gerrit service Route53 routing.
Parameters:
  Primary1ServiceStackName:
      Description: Stack name of the ECS Primary Gerrit service
      Type: String
      Default: gerrit-service-primary-1
  Primary2ServiceStackName:
      Description: Stack name of the ECS Primary Gerrit service
      Type: String
      Default: gerrit-service-primary-2
  LBServiceStackName:
      Description: Stack name of the ECS LB service
      Type: String
      Default: gerrit-service

Resources:

  ############
  ##  SSH   ##
  ############

  Primary1DnsRecordForSSH:
      Type: AWS::Route53::RecordSet
      Properties:
        Name:
          !Join
            - '.'
            - - !Join
                - '-'
                - - Fn::ImportValue: !Join [ ':', [ !Ref 'Primary1ServiceStackName', 'Subdomain' ] ]
                  - 'ssh'
              - Fn::ImportValue: !Join [':', [!Ref 'Primary1ServiceStackName', 'HostedZoneName']]
        HostedZoneName:
          !Join
            - ''
            - - Fn::ImportValue: !Join [':', [!Ref 'Primary1ServiceStackName', 'HostedZoneName']]
              - '.'
        Comment: DNS name for nlb serving SSH requests to primary gerrit 1
        Type: A
        AliasTarget:
          DNSName:
            Fn::ImportValue:
              !Join [':', [!Ref 'Primary1ServiceStackName', 'GerritSSHLoadBalancerDNSName']]
          HostedZoneId:
            Fn::ImportValue:
              !Join [':', [!Ref 'Primary1ServiceStackName', 'GerritSSHCanonicalHostedZoneID']]
          EvaluateTargetHealth: False

  Primary2DnsRecordForSSH:
      Type: AWS::Route53::RecordSet
      Properties:
        Name:
          !Join
            - '.'
            - - !Join
                - '-'
                - - Fn::ImportValue: !Join [ ':', [ !Ref 'Primary2ServiceStackName', 'Subdomain' ] ]
                  - 'ssh'
              - Fn::ImportValue: !Join [':', [!Ref 'Primary2ServiceStackName', 'HostedZoneName']]
        HostedZoneName:
          !Join
            - ''
            - - Fn::ImportValue: !Join [':', [!Ref 'Primary2ServiceStackName', 'HostedZoneName']]
              - '.'
        Comment: DNS name for nlb serving SSH requests to primary gerrit 2
        Type: A
        AliasTarget:
          DNSName:
            Fn::ImportValue:
              !Join [':', [!Ref 'Primary2ServiceStackName', 'GerritSSHLoadBalancerDNSName']]
          HostedZoneId:
            Fn::ImportValue:
              !Join [':', [!Ref 'Primary2ServiceStackName', 'GerritSSHCanonicalHostedZoneID']]
          EvaluateTargetHealth: False

  HaProxyDnsRecord:
      Type: AWS::Route53::RecordSet
      Properties:
        Name:
          !Join
            - '.'
            - - !Join
                - '-'
                - - Fn::ImportValue: !Join [ ':', [ !Ref 'LBServiceStackName', 'Subdomain' ] ]
                  - 'ssh'
              - Fn::ImportValue: !Join [':', [!Ref 'LBServiceStackName', 'HostedZoneName']]
        HostedZoneName:
          !Join
            - ''
            - - Fn::ImportValue: !Join [':', [!Ref 'LBServiceStackName', 'HostedZoneName']]
              - '.'
        Comment: DNS name for haproxy serving SSH requests to gerrit
        Type: A
        AliasTarget:
          DNSName:
            Fn::ImportValue:
              !Join [':', [!Ref 'LBServiceStackName', 'HaProxySSHLoadBalancerDNSName']]
          HostedZoneId:
            Fn::ImportValue:
              !Join [':', [!Ref 'LBServiceStackName', 'GerritSSHCanonicalHostedZoneID']]
          EvaluateTargetHealth: False

############
##  HTTP  ##
############

  Primary1DnsRecordForHTTP:
    Type: AWS::Route53::RecordSet
    Properties:
      Name:
        !Join
        - '.'
        - - !Join
            - '-'
            - - Fn::ImportValue: !Join [ ':', [ !Ref 'Primary1ServiceStackName', 'Subdomain' ] ]
              - 'http'
          - Fn::ImportValue: !Join [':', [!Ref 'Primary1ServiceStackName', 'HostedZoneName']]
      HostedZoneName:
        !Join
        - ''
        - - Fn::ImportValue: !Join [':', [!Ref 'Primary1ServiceStackName', 'HostedZoneName']]
          - '.'
      Comment: DNS name for nlb serving HTTP requests to primary gerrit 1
      Type: A
      AliasTarget:
        DNSName:
          Fn::ImportValue:
            !Join [':', [!Ref 'Primary1ServiceStackName', 'GerritHTTPLoadBalancerDNSName']]
        HostedZoneId:
          Fn::ImportValue:
            !Join [':', [!Ref 'Primary1ServiceStackName', 'GerritHTTPCanonicalHostedZoneID']]
        EvaluateTargetHealth: False

  Primary2DnsRecordForHTTP:
    Type: AWS::Route53::RecordSet
    Properties:
      Name:
        !Join
        - '.'
        - - !Join
            - '-'
            - - Fn::ImportValue: !Join [ ':', [ !Ref 'Primary2ServiceStackName', 'Subdomain' ] ]
              - 'http'
          - Fn::ImportValue: !Join [':', [!Ref 'Primary2ServiceStackName', 'HostedZoneName']]
      HostedZoneName:
        !Join
        - ''
        - - Fn::ImportValue: !Join [':', [!Ref 'Primary2ServiceStackName', 'HostedZoneName']]
          - '.'
      Comment: DNS name for nlb serving HTTP requests to primary gerrit 2
      Type: A
      AliasTarget:
        DNSName:
          Fn::ImportValue:
            !Join [':', [!Ref 'Primary2ServiceStackName', 'GerritHTTPLoadBalancerDNSName']]
        HostedZoneId:
          Fn::ImportValue:
            !Join [':', [!Ref 'Primary2ServiceStackName', 'GerritHTTPCanonicalHostedZoneID']]
        EvaluateTargetHealth: False