# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    static_configs:
    - targets: ['localhost:9090']


  - job_name: 'gerrit-master-javamelody'

    scheme: https
    metrics_path: '/monitoring'

    params:
      format: ['prometheus']

    bearer_token: {{PROMETHEUS_BEARER_TOKEN}}

    scrape_interval: 1s

    static_configs:
      - targets: ['gerrit-master.gerrit-demo.gerritforgeaws.com:443']
        labels:
          env: 'unit'

  - job_name: 'gerrit-master-metrics'

    scheme: https
    metrics_path: '/plugins/metrics-reporter-prometheus/metrics'

    params:
      format: ['prometheus']

    bearer_token: {{PROMETHEUS_BEARER_TOKEN}}

    scrape_interval: 5s

    static_configs:
      - targets: ['gerrit-master.gerrit-demo.gerritforgeaws.com:443']
        labels:
          env: 'unit'

  - job_name: 'gerrit-slave-javamelody'

    scheme: https
    metrics_path: '/monitoring'

    params:
      format: ['prometheus']

    bearer_token: {{PROMETHEUS_BEARER_TOKEN}}

    scrape_interval: 1s

    static_configs:
      - targets: ['gerrit-slave.gerrit-demo.gerritforgeaws.com:443']
        labels:
          env: 'unit'

  - job_name: 'gerrit-slave-metrics'

    scheme: https
    metrics_path: '/plugins/metrics-reporter-prometheus/metrics'

    params:
      format: ['prometheus']

    bearer_token: {{PROMETHEUS_BEARER_TOKEN}}

    scrape_interval: 5s

    static_configs:
      - targets: ['gerrit-slave.gerrit-demo.gerritforgeaws.com:443']
        labels:
          env: 'unit'
