AWSTemplateFormatVersion: '2010-09-09'
Description: A stack for the Gerrit service Route53 routing.
Parameters:
  ServiceStackName:
      Description: Stack name of the ECS Gerrit service
      Type: String
      Default: gerrit-service

Resources:
  DnsRecord:
      Type: AWS::Route53::RecordSet
      Properties:
        Name:
          !Join
            - '.'
            - - Fn::ImportValue: !Join [':', [!Ref 'ServiceStackName', 'Subdomain']]
              - Fn::ImportValue: !Join [':', [!Ref 'ServiceStackName', 'HostedZoneName']]
        HostedZoneName:
          !Join
            - ''
            - - Fn::ImportValue: !Join [':', [!Ref 'ServiceStackName', 'HostedZoneName']]
              - '.'
        Comment: DNS name for Gerrit Master.
        Type: A
        AliasTarget:
          DNSName:
            Fn::ImportValue:
              !Join [':', [!Ref 'ServiceStackName', 'PublicLoadBalancerDNSName']]
          HostedZoneId:
            Fn::ImportValue:
              !Join [':', [!Ref 'ServiceStackName', 'CanonicalHostedZoneID']]
          EvaluateTargetHealth: False
